#!/bin/sh

# The file contents isn't my work. I keep it here to avoid looking for answers in case of nuking.

# Create trackpadfix.service with content.
cat /etc/systemd/system/trackpadpadfix.service 
"[Unit]
Description=Bind trackpad to correct driver

[Service]
ExecStart=/usr/local/bin/touchpadfix
Type=oneshot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target"

# Create trackpadfix. 
cat /usr/local/bin/trackpadfix
# Content of trackpadfix file.
"#!/bin/sh
modprobe i2c_hid 
echo "i2c-ELAN0001:00" > /sys/bus/i2c/drivers/elants_i2c/unbind
echo "i2c-ELAN0001:00" > /sys/bus/i2c/drivers/i2c_hid/bind > /usr/local/bin/touchpadfix
chmod + x /usr/local/bin/trackpadfix"


systemctl daemon-reload

systemctl enable --now touchpadfix.service
